#define TAPPING_TERM 175
#define PERMISSIVE_HOLD

#define CHARYBDIS_POINTER_ACCELERATION_ENABLE
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1000
#define CHARYBDIS_MINIMUM_SNIPING_DPI 500
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y

#define BILATERAL_COMBINATIONS 200
